server:
  port: 8080
spring:
  profiles:
    active: local
  pid:
    file: application.pid
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_laziness: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
